[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd backend && npm ci --prefer-offline --no-audit']

[phases.build]
cmds = ['echo "No build step needed"']

[start]
cmd = 'cd backend && npm start'
